apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    email: hello@sudhanva.me
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-issuer-account-key
    solvers:
    - http01:
        gatewayHTTPRoute:
              parentRefs:
              - name: docs-gateway
                namespace: default
                kind: Gateway
                group: gateway.networking.k8s.io
